services:
  - type: web
    name: culture-benin-web
    env: docker
    repo: https://github.com/ulrichdohodev/culture-benin
    branch: main
    plan: free

    dockerfilePath: ./Dockerfile.render

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_NAME
        value: CultureBenin

      - key: PORT
        value: "8080"

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        value: mysql.railway.internal

      - key: DB_PORT
        value: "3306"

      - key: DB_DATABASE
        value: railway

      - key: DB_USERNAME
        value: root

      - key: DB_PASSWORD
        sync: false   # sera ajouté manuellement sur Render

      - key: APP_KEY
        sync: false   # sera ajouté manuellement sur Render
